import Head from "next/head";
import { type NextPage } from "next";

import { useRouter } from "next/router";

import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../../utils/api";

const Home: NextPage = () => {
  const router = useRouter();

  const { id } = router.query;

  const hello = api.example.content.useQuery({
    id: id as string,
  });

  console.log(hello.data);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">{id}</p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
